version: 2
updates:
  - package-ecosystem: 'yarn'
    directory: 'back-end/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'yarn'
    directory: 'front-end/'
    schedule:
      interval: 'weekly'
