version: "3.8"
services:
  dev-container:
    container_name: PrivateNetwork
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        sleep infinity
    volumes:
      - ../..:/workspaces:cached
      - ${PATH_TO_HOSTS_YML}:/home/node/.config/gh/hosts.yml:ro
