version: "3.8"
services:
  dev-container:
    container_name: PrivateNetwork
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        sleep infinity
    volumes:
      - ../..:/workspaces:cached
      - ~/AppData/Roaming/GitHub CLI/hosts.yml:/home/node/.config/gh/hosts.yml:ro
